"""Cross-implementation conformance tests.

These tests prove the Python ``qrs`` core is *wire-compatible* with the reference
TypeScript ``qrs-core`` implementation. They consume the shared golden-vector
fixture (``src/qrs-conformance/fixtures/golden.json``) and assert that the Python
implementation produces byte-identical output for identical inputs.

The fixture is generated by ``src/qrs-conformance/generate-fixtures.mjs`` (the
TypeScript reference). Regenerate it after any wire-format change:

    node src/qrs-conformance/generate-fixtures.mjs

Run these tests with the rest of the suite:

    PYTHONPATH=src pytest tests/test_conformance.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from qrs.cbor import cbor_decode, cbor_encode
from qrs.crypto.ecdsaP256 import EcdsaP256Provider
from qrs.crypto.ed25519 import Ed25519Provider
from qrs.crypto.jwk import canonical_public_key_bytes
from qrs.crypto.providers import compute_key_id
from qrs.envelope import sdoc_id_of, tcert_id_of
from qrs.id import (
    from_hex,
    hash_for,
    is_hash_algorithm,
    sha256,
    sha384,
    sha3_512,
    to_hex,
    trunc_sha256,
)
from qrs.transfer import (
    decode_bundle,
    decode_qrs_file,
    decode_transfer_payload,
    encode_bundle,
    encode_qrs_bundle_file,
    encode_qrs_file,
    encode_transfer_payload,
)

FIXTURE_PATH = Path(__file__).resolve().parents[2] / "qrs-conformance" / "fixtures" / "golden.json"


@pytest.fixture(scope="module")
def golden() -> dict:
    if not FIXTURE_PATH.exists():
        pytest.skip(
            "golden.json not found; run `node src/qrs-conformance/generate-fixtures.mjs` first"
        )
    with open(FIXTURE_PATH, encoding="utf-8") as fh:
        return json.load(fh)


# --------------------------------------------------------------------------- #
# Canonical CBOR
# --------------------------------------------------------------------------- #


def test_cbor_vectors_match(golden):
    """Python canonical CBOR must byte-match the reference for every vector."""
    cases = {
        "null": None,
        "true": True,
        "false": False,
        "zero": 0,
        "one": 1,
        "negOne": -1,
        "int23": 23,
        "int24": 24,
        "int255": 255,
        "int256": 256,
        "int65535": 65535,
        "int65536": 65536,
        "intMax32": 0xFFFFFFFF,
        "intMax64": 0xFFFFFFFFFFFFFFFF,
        "neg100": -100,
        "negMax64": -(2**63),
        "text": "hello",
        "textUnicode": "héllo 世界",
        "bytes": bytes([0, 1, 2, 255]),
        "array": [1, "two", [3, 4], None],
        "mapSorted": {"b": 1, "a": 2, "c": {"z": 0, "y": 1}},
        "mapIntKeys": {1: "one", 2: "two"},
        "nested": {"a": [1, {"b": "x"}], "c": bytes([9, 8])},
    }
    for name, value in cases.items():
        assert to_hex(cbor_encode(value)) == golden["cbor"][name], f"cbor vector {name}"


def test_cbor_decode_vectors_match(golden):
    """Python must decode the reference's canonical bytes back to the same value."""
    for name, value in {
        "null": None,
        "true": True,
        "false": False,
        "zero": 0,
        "one": 1,
        "negOne": -1,
        "int23": 23,
        "int24": 24,
        "int255": 255,
        "int256": 256,
        "int65535": 65535,
        "int65536": 65536,
        "intMax32": 0xFFFFFFFF,
        "intMax64": 0xFFFFFFFFFFFFFFFF,
        "neg100": -100,
        "negMax64": -(2**63),
        "text": "hello",
        "textUnicode": "héllo 世界",
        "bytes": bytes([0, 1, 2, 255]),
        "array": [1, "two", [3, 4], None],
        "mapSorted": {"b": 1, "a": 2, "c": {"z": 0, "y": 1}},
        "mapIntKeys": {1: "one", 2: "two"},
        "nested": {"a": [1, {"b": "x"}], "c": bytes([9, 8])},
    }.items():
        assert cbor_decode(from_hex(golden["cbor"][name])) == value, f"cbor decode {name}"


# --------------------------------------------------------------------------- #
# Hashing
# --------------------------------------------------------------------------- #


def test_hash_vectors_match(golden):
    data = b"qrs"
    assert to_hex(sha256(data)) == golden["hashes"]["sha256"]
    assert to_hex(sha384(data)) == golden["hashes"]["sha384"]
    assert to_hex(sha3_512(data)) == golden["hashes"]["sha3_512"]
    assert to_hex(hash_for(None, data)) == golden["hashes"]["hashForDefault"]
    assert to_hex(hash_for("SHA-384", data)) == golden["hashes"]["hashForSha384"]
    assert to_hex(trunc_sha256(data)) == golden["hashes"]["truncSha256"]


# --------------------------------------------------------------------------- #
# Key derivation (fixed keys → identical key_id across languages)
# --------------------------------------------------------------------------- #


def test_ed25519_key_derivation_matches(golden):
    provider = Ed25519Provider()
    public_jwk = golden["keys"]["ed25519"]["publicJwk"]
    assert to_hex(canonical_public_key_bytes(public_jwk)) == golden["keys"]["ed25519"]["canonicalPublicKey"]
    assert provider.key_id(public_jwk) == golden["keys"]["ed25519"]["keyId"]
    assert compute_key_id(provider, public_jwk) == golden["keys"]["ed25519"]["keyId"]


def test_ecdsa_key_derivation_matches(golden):
    provider = EcdsaP256Provider()
    public_jwk = golden["keys"]["ecdsaP256"]["publicJwk"]
    assert to_hex(canonical_public_key_bytes(public_jwk)) == golden["keys"]["ecdsaP256"]["canonicalPublicKey"]
    assert provider.key_id(public_jwk) == golden["keys"]["ecdsaP256"]["keyId"]


# --------------------------------------------------------------------------- #
# Identifier derivation
# --------------------------------------------------------------------------- #


def test_identifier_vectors_match(golden):
    ed_key_id = golden["keys"]["ed25519"]["keyId"]
    ec_key_id = golden["keys"]["ecdsaP256"]["keyId"]
    assert tcert_id_of(ed_key_id, 1) == golden["ids"]["tcertIdEd"]
    assert tcert_id_of(ec_key_id, 7) == golden["ids"]["tcertIdEc"]
    assert sdoc_id_of(bytes([1, 2, 3, 4])) == golden["ids"]["sdocId"]


# --------------------------------------------------------------------------- #
# Transfer envelope
# --------------------------------------------------------------------------- #


def test_transfer_vectors_match(golden):
    assert encode_transfer_payload("sdoc", "aGVsbG8") == golden["transfer"]["payload"]
    assert encode_bundle(
        [{"type": "tcert", "bytes_b64": "dGNlcnQ"}, {"type": "sdoc", "bytes_b64": "c2RvYw"}]
    ) == golden["transfer"]["bundle"]
    assert to_hex(encode_qrs_file("tcert", "dGNlcnQ")) == golden["transfer"]["qrsFile"]
    assert to_hex(encode_qrs_bundle_file([{"type": "statement", "bytes_b64": "c3RhdGU"}])) == golden[
        "transfer"
    ]["qrsBundleFile"]


def test_transfer_decode_roundtrip():
    payload = encode_transfer_payload("sdoc", "aGVsbG8")
    decoded = decode_transfer_payload(payload)
    assert decoded is not None
    assert decoded.type == "sdoc"
    assert decoded.bytes_b64 == "aGVsbG8"

    bundle = encode_bundle([{"type": "tcert", "bytes_b64": "dGNlcnQ"}])
    decoded_bundle = decode_bundle(bundle)
    assert decoded_bundle is not None
    assert decoded_bundle.objects[0].type == "tcert"
    assert decoded_bundle.objects[0].bytes_b64 == "dGNlcnQ"

    qrs = decode_qrs_file(encode_qrs_file("tcert", "dGNlcnQ").decode("utf-8"))
    assert qrs is not None
    assert qrs["kind"] == "object"
    assert qrs["payload"].type == "tcert"


def test_transfer_rejects_foreign_payloads():
    assert decode_transfer_payload("https://example.com/x") is None
    assert decode_transfer_payload("qrs://v1/unknown/aGVsbG8") is None
    assert decode_bundle("qrs://v1/bundle/not-base64") is None
    assert decode_qrs_file("") is None


# --------------------------------------------------------------------------- #
# Bidirectional cross-verification (Python signs → JS verifies, and vice versa)
# --------------------------------------------------------------------------- #

import asyncio  # noqa: E402
import base64  # noqa: E402
import subprocess  # noqa: E402
import sys  # noqa: E402

from qrs.context import DummyContextProvider  # noqa: E402
from qrs.fields import FieldSchema  # noqa: E402
from qrs.runtime import QrsDependencies, create_qrs  # noqa: E402
from qrs.services.certificateService import CreateTcertParams  # noqa: E402
from qrs.services.signingService import IssueSdocParams  # noqa: E402

CONFORMANCE_DIR = Path(__file__).resolve().parents[2] / "qrs-conformance"
JS_VERIFIER = CONFORMANCE_DIR / "verify_js.mjs"
JS_CORE_DIR = Path(__file__).resolve().parents[2] / "qrs-core-js"


def _b64(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _verify_in_js(request: dict) -> dict:
    """Run the JS verifier bridge with a JSON request; return the parsed verdict."""
    result = subprocess.run(
        ["node", str(JS_VERIFIER)],
        input=json.dumps(request),
        capture_output=True,
        text=True,
        cwd=str(CONFORMANCE_DIR),
    )
    assert result.returncode == 0, f"node verifier failed: {result.stderr}"
    return json.loads(result.stdout)


async def _make_pair(algorithm: str) -> tuple[bytes, bytes, dict]:
    """Create a TCert + SDoc in Python; return (tcert_bytes, sdoc_bytes, public_jwk)."""
    qrs = create_qrs(
        QrsDependencies(context_provider=DummyContextProvider(secrets={"pin": "s3cret"}))
    )
    tcert = await qrs.certificates.create_tcert(
        CreateTcertParams(
            algorithm=algorithm,
            name="AFDA",
            fields=[
                FieldSchema(type="text", name="license_no", label="License"),
                FieldSchema(type="secretInput", name="pin", label="PIN"),
            ],
        )
    )
    await qrs.trust.pin(tcert.tcert_id)
    issued = await qrs.signing.issue_sdoc(
        IssueSdocParams(
            tcert_id=tcert.tcert_id,
            values={"license_no": "AFDA-123", "pin": "s3cret"},
        )
    )
    from qrs.envelope import parse_signed_object

    public_jwk = parse_signed_object(tcert.bytes).data["publicKey"]
    return tcert.bytes, issued.bytes, public_jwk


@pytest.mark.parametrize("algorithm", ["Ed25519", "ECDSA-P256"])
def test_python_signed_objects_verify_in_js(algorithm):
    """Objects signed by the Python core must verify in the reference JS core."""
    tcert_bytes, sdoc_bytes, public_jwk = asyncio.run(_make_pair(algorithm))

    tcert_verdict = _verify_in_js({"bytesB64": _b64(tcert_bytes), "type": "tcert"})
    assert tcert_verdict["ok"] is True
    assert tcert_verdict["verified"] is True
    assert tcert_verdict["type"] == "tcert"

    sdoc_verdict = _verify_in_js(
        {
            "bytesB64": _b64(sdoc_bytes),
            "type": "sdoc",
            "publicKey": public_jwk,
            "secret": {"pin": "s3cret"},
        }
    )
    assert sdoc_verdict["ok"] is True
    assert sdoc_verdict["verified"] is True
    assert sdoc_verdict["type"] == "sdoc"


@pytest.mark.parametrize("algorithm", ["Ed25519", "ECDSA-P256"])
def test_js_signed_objects_verify_in_python(algorithm):
    """Objects signed by the reference JS core must verify in the Python core."""
    # Produce a JS-signed TCert + SDoc via the JS core, then verify in Python.
    script = f"""
import {{ createQrs }} from '{JS_CORE_DIR}/dist/runtime.js';
import {{ DummyContextProvider }} from '{JS_CORE_DIR}/dist/context/dummyContext.js';
import {{ parseSignedObject }} from '{JS_CORE_DIR}/dist/signedObject/signedObject.js';
import {{ toBase64Url }} from '{JS_CORE_DIR}/dist/id.js';
const rt = createQrs({{ contextProvider: new DummyContextProvider({{ secrets: {{ pin: 's3cret' }} }}) }});
const tcert = await rt.certificates.createTcert({{ algorithm: '{algorithm}', name: 'AFDA', fields: [
  {{ type: 'text', name: 'license_no', label: 'License' }},
  {{ type: 'secretInput', name: 'pin', label: 'PIN' }},
]}});
await rt.trust.pin(tcert.tcertId);
const issued = await rt.signing.issueSdoc({{ tcertId: tcert.tcertId, values: {{ license_no: 'AFDA-123', pin: 's3cret' }} }});
const pub = parseSignedObject(tcert.bytes).data.publicKey;
console.log(JSON.stringify({{ tcert: toBase64Url(tcert.bytes), sdoc: toBase64Url(issued.bytes), publicKey: pub }}));
"""
    result = subprocess.run(
        ["node", "--input-type=module", "-e", script],
        capture_output=True,
        text=True,
        cwd=str(JS_CORE_DIR),
    )
    assert result.returncode == 0, f"node producer failed: {result.stderr}"
    produced = json.loads(result.stdout)

    from qrs.envelope import parse_signed_object, verify_parsed_signed_object
    from qrs.crypto.registry import create_default_crypto_registry
    from qrs.id import from_base64url
    from qrs.cbor import cbor_encode

    # TCert self-signature must verify in Python.
    tcert_bytes = from_base64url(produced["tcert"])
    tcert_parsed = parse_signed_object(tcert_bytes)
    registry = create_default_crypto_registry()
    provider = registry.get(tcert_parsed.algorithm)
    assert verify_parsed_signed_object(tcert_parsed, provider, tcert_parsed.data["publicKey"]) is True

    # SDoc signature must verify in Python (with the secret AAD).
    sdoc_bytes = from_base64url(produced["sdoc"])
    sdoc_parsed = parse_signed_object(sdoc_bytes)
    aad = cbor_encode({"pin": "s3cret"})
    assert verify_parsed_signed_object(sdoc_parsed, provider, produced["publicKey"], aad) is True