/**
 * Cross-implementation conformance tests (TypeScript side).
 *
 * Two layers:
 *  1. Golden-vector self-check: the reference implementation must reproduce the
 *     shared `golden.json` fixture byte-for-byte.
 *  2. Bidirectional cross-verification: objects signed by the Python core must
 *     verify here, and objects signed here must verify in the Python core.
 *
 * The fixture is generated by `src/qrs-conformance/generate-fixtures.mjs`.
 * The Python verifier bridge is `src/qrs-conformance/verify_python.py`.
 */
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cborEncode } from '../src/cbor/canonical.js';
import { toHex, truncSha256, sha256, sha384, sha3_512, hashFor } from '../src/id.js';
import { canonicalPublicKeyBytes } from '../src/crypto/jwk.js';
import { Ed25519Provider } from '../src/crypto/ed25519.js';
import { EcdsaP256Provider } from '../src/crypto/ecdsaP256.js';
import { tcertIdOf, sdocIdOf } from '../src/signedObject/signedObject.js';
import { encodeTransferPayload, encodeBundle, encodeQrsFile, encodeQrsBundleFile } from '../src/transfer.js';
import { createQrs } from '../src/runtime.js';
import { DummyContextProvider } from '../src/context/dummyContext.js';
import { parseSignedObject } from '../src/signedObject/signedObject.js';
import { toBase64Url } from '../src/id.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE = JSON.parse(
  readFileSync(join(__dirname, '..', '..', 'qrs-conformance', 'fixtures', 'golden.json'), 'utf8')
);
const PY_VERIFIER = join(__dirname, '..', '..', 'qrs-conformance', 'verify_python.py');
const PY_VENV_PYTHON = join(__dirname, '..', '..', 'qrs-core-python', '.venv', 'bin', 'python');

/** Run the Python verifier bridge with a JSON request; return the parsed verdict. */
function verifyInPython(request: Record<string, unknown>): Record<string, unknown> {
  const out = execFileSync(PY_VENV_PYTHON, [PY_VERIFIER], {
    input: JSON.stringify(request),
    encoding: 'utf8',
  });
  return JSON.parse(out);
}

describe('conformance: golden vectors (self-check)', () => {
  it('canonical CBOR matches the shared fixture', () => {
    const cases: Record<string, unknown> = {
      null: null,
      true: true,
      false: false,
      zero: 0,
      one: 1,
      negOne: -1,
      int23: 23,
      int24: 24,
      int255: 255,
      int256: 256,
      int65535: 65535,
      int65536: 65536,
      intMax32: 0xffffffff,
      intMax64: 0xffffffffffffffffn,
      neg100: -100,
      negMax64: -(2n ** 63n),
      text: 'hello',
      textUnicode: 'héllo 世界',
      bytes: Uint8Array.from([0, 1, 2, 255]),
      array: [1, 'two', [3, 4], null],
      mapSorted: { b: 1, a: 2, c: { z: 0, y: 1 } },
      mapIntKeys: new Map([[1, 'one'], [2, 'two']]),
      nested: { a: [1, { b: 'x' }], c: Uint8Array.from([9, 8]) },
    };
    for (const [name, value] of Object.entries(cases)) {
      expect(toHex(cborEncode(value as never))).toBe(FIXTURE.cbor[name]);
    }
  });

  it('hashing matches the shared fixture', () => {
    const data = new TextEncoder().encode('qrs');
    expect(toHex(sha256(data))).toBe(FIXTURE.hashes.sha256);
    expect(toHex(sha384(data))).toBe(FIXTURE.hashes.sha384);
    expect(toHex(sha3_512(data))).toBe(FIXTURE.hashes.sha3_512);
    expect(toHex(hashFor(undefined, data))).toBe(FIXTURE.hashes.hashForDefault);
    expect(toHex(hashFor('SHA-384', data))).toBe(FIXTURE.hashes.hashForSha384);
    expect(toHex(truncSha256(data))).toBe(FIXTURE.hashes.truncSha256);
  });

  it('key derivation matches the shared fixture', () => {
    const ed = new Ed25519Provider();
    const ec = new EcdsaP256Provider();
    expect(toHex(canonicalPublicKeyBytes(FIXTURE.keys.ed25519.publicJwk))).toBe(FIXTURE.keys.ed25519.canonicalPublicKey);
    expect(ed.keyId(FIXTURE.keys.ed25519.publicJwk)).toBe(FIXTURE.keys.ed25519.keyId);
    expect(toHex(canonicalPublicKeyBytes(FIXTURE.keys.ecdsaP256.publicJwk))).toBe(FIXTURE.keys.ecdsaP256.canonicalPublicKey);
    expect(ec.keyId(FIXTURE.keys.ecdsaP256.publicJwk)).toBe(FIXTURE.keys.ecdsaP256.keyId);
  });

  it('identifier derivation matches the shared fixture', () => {
    expect(tcertIdOf(FIXTURE.keys.ed25519.keyId, 1)).toBe(FIXTURE.ids.tcertIdEd);
    expect(tcertIdOf(FIXTURE.keys.ecdsaP256.keyId, 7)).toBe(FIXTURE.ids.tcertIdEc);
    expect(sdocIdOf(Uint8Array.from([1, 2, 3, 4]))).toBe(FIXTURE.ids.sdocId);
  });

  it('transfer envelope matches the shared fixture', () => {
    expect(encodeTransferPayload('sdoc', 'aGVsbG8')).toBe(FIXTURE.transfer.payload);
    expect(
      encodeBundle([
        { type: 'tcert', bytesB64: 'dGNlcnQ' },
        { type: 'sdoc', bytesB64: 'c2RvYw' },
      ])
    ).toBe(FIXTURE.transfer.bundle);
    expect(toHex(encodeQrsFile('tcert', 'dGNlcnQ'))).toBe(FIXTURE.transfer.qrsFile);
    expect(toHex(encodeQrsBundleFile([{ type: 'statement', bytesB64: 'c3RhdGU' }]))).toBe(
      FIXTURE.transfer.qrsBundleFile
    );
  });
});

describe('conformance: bidirectional cross-verification', () => {
  const algorithms = ['Ed25519', 'ECDSA-P256'] as const;

  for (const algorithm of algorithms) {
    it(`JS-signed TCert + SDoc verify in Python (${algorithm})`, async () => {
      const rt = createQrs({
        contextProvider: new DummyContextProvider({ secrets: { pin: 's3cret' } }),
      });
      const tcert = await rt.certificates.createTcert({
        algorithm,
        name: 'AFDA',
        fields: [
          { type: 'text', name: 'license_no', label: 'License' },
          { type: 'secretInput', name: 'pin', label: 'PIN' },
        ],
      });
      await rt.trust.pin(tcert.tcertId);
      const issued = await rt.signing.issueSdoc({
        tcertId: tcert.tcertId,
        values: { license_no: 'AFDA-123', pin: 's3cret' },
      });

      const tcertParsed = parseSignedObject(tcert.bytes);
      const publicKey = tcertParsed.data.publicKey;

      // TCert self-signature must verify in Python.
      const tcertVerdict = verifyInPython({ bytesB64: toBase64Url(tcert.bytes), type: 'tcert' });
      expect(tcertVerdict.ok).toBe(true);
      expect(tcertVerdict.verified).toBe(true);
      expect(tcertVerdict.type).toBe('tcert');

      // SDoc signature must verify in Python (with the secret AAD).
      const sdocVerdict = verifyInPython({
        bytesB64: toBase64Url(issued.bytes),
        type: 'sdoc',
        publicKey,
        secret: { pin: 's3cret' },
      });
      expect(sdocVerdict.ok).toBe(true);
      expect(sdocVerdict.verified).toBe(true);
      expect(sdocVerdict.type).toBe('sdoc');
      expect(sdocVerdict.signerKeyId).toBe(tcertParsed.signerKeyId);
    });
  }
});