# Generated by Django 6.1 on 2026-08-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_alter_sdocrecord_tcert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_sign', 'Can sign an SDoc via API'), ('can_revoke_tcert', 'Can revoke a TCert'), ('can_block_sdoc', 'Can block an SDoc'), ('can_unblock_sdoc', 'Can unblock an SDoc')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
