# Generated by Django 6.1 on 2026-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('enterprise', '0003_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='permissions',
        ),
        migrations.AddField(
            model_name='apikey',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='api_keys', to='auth.permission', verbose_name='Permissions'),
        ),
    ]
