# Generated by Django 6.1 on 2026-08-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedTcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=64, unique=True)),
                ('certificate_number', models.IntegerField()),
                ('tcert_id', models.CharField(max_length=80, unique=True)),
                ('algorithm', models.CharField(max_length=32)),
                ('issuer_name', models.CharField(blank=True, max_length=255)),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('public_key', models.JSONField(default=dict)),
                ('online_endpoint', models.CharField(blank=True, max_length=500)),
                ('tcert_b64', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TcertChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(db_index=True, max_length=64)),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('difficulty', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TcertToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(db_index=True, max_length=64)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('key_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=128)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('content_b64', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tcert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='api.supportedtcert')),
            ],
        ),
        migrations.CreateModel(
            name='SignedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('signed_at', models.BigIntegerField(default=0)),
                ('bytes_b64', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('tcert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='api.supportedtcert')),
            ],
            options={
                'ordering': ['signed_at'],
                'constraints': [models.UniqueConstraint(fields=('tcert', 'statement_id'), name='unique_statement_per_tcert')],
            },
        ),
    ]
