# Generated by Django 6.1 on 2026-08-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='content_b64',
            new_name='bytes_b64',
        ),
        migrations.AddField(
            model_name='attachment',
            name='signed_at',
            field=models.BigIntegerField(default=0),
        ),
    ]
