# Generated by Django 6.1 on 2026-08-26 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attachment_object_b64'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcertAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_id', models.CharField(max_length=64)),
                ('tcert_hash', models.CharField(blank=True, default='', max_length=64)),
                ('signed_at', models.IntegerField(default=0)),
                ('bytes_b64', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_targets', to='api.supportedtcert')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='api.supportedtcert')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('ca', 'target', 'statement_id')},
            },
        ),
    ]
