# Generated by Django 6.1 on 2026-08-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_content_b64_attachment_bytes_b64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportedtcert',
            name='key_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
