# Generated by Django 6.1 on 2026-08-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_supportedtcert_key_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportedtcert',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='supportedtcert',
            name='issuer_name',
        ),
        migrations.AddField(
            model_name='supportedtcert',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
