# Generated by Django 6.1 on 2026-08-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_supportedtcert_document_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='bytes_b64',
        ),
        migrations.AddField(
            model_name='attachment',
            name='content',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
